[[module]]
name = "wasix-axum"
source = "target/wasm32-wasmer-wasi/release/wasix-axum.wasm"

[[command]]
name = "wasix-axum"
module = "wasix-axum"
runner = "wasi@unstable_"

[package]
name = "abdebek/wasmer-axum-starter-77c"
version = "0.1.3"
description = "Package for wasmer axum starter"
wasmer-extra-flags = "--net --enable-threads --enable-bulk-memory"
repository = "https://github.com/abdebek/wasmer-axum-starter-77c"

[dependencies]
